app = "svit-gateway"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  script_checks = []
  tcp_checks = []
  internal_port = 80
  processes = ["app"]
  
  [[services.ports]]
    port = 80

[[services]]
  http_checks = []
  script_checks = []
  tcp_checks = []
  internal_port = 443
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 443
    
[[services]]
  http_checks = []
  script_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 10001